language: node_js

node_js: 'stable'

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

cache:
  directories:
    - node_modules
    - citation-backoffice/node_modules
    - citation-demo/node_modules
    - citation-react-renderer/node_modules
    - citation-react-router/node_modules
    - citation-server/node_modules

script:
  - npm run bootstrap
  - npm run build
  - npm run lint
  - npm test

after_success:
  - if [ "$TRAVIS_BRANCH" == "docker" ]; then
    rm -rf node_modules;
    rm -rf citation-backoffice/node_modules;
    rm -rf citation-demo/node_modules;
    rm -rf citation-react-renderer/node_modules;
    rm -rf citation-react-router/node_modules;
    rm -rf citation-server/node_modules;
    docker build -t ayaxp/citation .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ayaxp/citation;
    fi
