language: node_js
node_js: stable

services:
- docker

addons:
  ssh_known_hosts: lux-buisine.fr
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-4.9-dev

cache:
  directories:
  - node_modules
  - citation-backoffice/node_modules
  - citation-demo/node_modules
  - citation-react-renderer/node_modules
  - citation-react-router/node_modules
  - citation-server/node_modules

script:
- npm run bootstrap
- npm run build
- npm run lint
- npm test

after_success:
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
  rm -rf node_modules;
  rm -rf citation-backoffice/node_modules;
  rm -rf citation-demo/node_modules;
  rm -rf citation-react-renderer/node_modules;
  rm -rf citation-react-router/node_modules;
  rm -rf citation-server/node_modules;
  docker build -t ayaxp/citation .;
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push ayaxp/citation;
  fi

before_deploy:
- openssl aes-256-cbc -K $encrypted_c6be0e250573_key -iv $encrypted_c6be0e250573_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: ssh lux-buisine.fr '/home/swiip/docker/deploy-citation.sh'
  on:
    branch: master
